# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: "healthcheck_api"
    scheme: https                      # ğŸ” Î§ÏÎ·ÏƒÎ¹Î¼Î¿Ï€Î¿Î¹Î¿ÏÎ¼Îµ HTTPS
    metrics_path: /metrics             # âœ… default, Î±Î»Î»Î¬ Ï„Î¿ Î²Î¬Î¶Î¿Ï…Î¼Îµ ÎºÎ±Î¸Î±ÏÎ¬
    tls_config:
      insecure_skip_verify: true       # ğŸ”“ Î‘Î³Î½Î¿ÎµÎ¯ Ï„Î¿ self-signed certificate
    static_configs:
      - targets: ["localhost:7057"]
        labels:
          app: "healthcheck-api"
